import { CartProvider } from "@/context/CartContext";
import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es">
        <body>
        <CartProvider>
            {children}
        </CartProvider>
        </body>
        </html>
    );
}
